env:
  global:
    - NDK_VERSION=r10e
    - FUSE_VERSION=0.21.0.6650
    - UNOPROJ=dropbox_example
    - NAME=DropboxExample
language: 
  - fuse
  - objective-c
  - android
  - node_js
os:
  - osx
sudo: required

cache:
  directories:
#    - /Applications/Fuse.app
#    - /usr/local/share/uno
#    - $HOME/.fuse
    - $HOME/Library/Android
#    - $HOME/fuse

before_install:
  - ./.travis/install-ndk.sh
  - ./.travis/install-fuse.sh
  - ./.travis/install-fuseandroid.sh
  - ./.travis/install-fusepm.sh

before_script:
  - cat ${UNOPROJ}.unoproj
  - fusepm install --unoproj ${UNOPROJ}.unoproj
  - cat ${UNOPROJ}.unoproj
  - find

script:
  - ./.travis/test_uno.sh
  - ./.travis/test_ios.sh
  - ./.travis/test_android.sh
